CREATE TABLE IF NOT EXISTS qiling_users (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    username VARCHAR(60) NOT NULL,
    email VARCHAR(120) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role_key VARCHAR(32) NOT NULL DEFAULT 'admin',
    token_version INT NOT NULL DEFAULT 1,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    wp_user_id BIGINT UNSIGNED DEFAULT NULL,
    login_failed_attempts INT NOT NULL DEFAULT 0,
    login_lock_until DATETIME NULL,
    last_login_at DATETIME NULL,
    last_login_ip VARCHAR(64) NOT NULL DEFAULT '',
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_qiling_users_username (username),
    UNIQUE KEY uq_qiling_users_email (email),
    KEY idx_qiling_users_wp_user_id (wp_user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS qiling_roles (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    role_key VARCHAR(64) NOT NULL,
    role_name VARCHAR(100) NOT NULL,
    permissions_json JSON NULL,
    is_system TINYINT(1) NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_qiling_roles_role_key (role_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS qiling_auth_ip_guards (
    ip_address VARCHAR(64) NOT NULL,
    window_started_at DATETIME NULL,
    window_request_count INT NOT NULL DEFAULT 0,
    locked_until DATETIME NULL,
    created_at DATETIME NULL,
    updated_at DATETIME NULL,
    PRIMARY KEY (ip_address),
    KEY idx_qiling_auth_ip_guards_locked_until (locked_until)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS qiling_stores (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    store_code VARCHAR(32) NOT NULL,
    store_name VARCHAR(120) NOT NULL,
    contact_name VARCHAR(60) NOT NULL DEFAULT '',
    contact_phone VARCHAR(30) NOT NULL DEFAULT '',
    address VARCHAR(255) NOT NULL DEFAULT '',
    open_time VARCHAR(20) NOT NULL DEFAULT '',
    close_time VARCHAR(20) NOT NULL DEFAULT '',
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_qiling_stores_store_code (store_code),
    KEY idx_qiling_stores_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS qiling_staff (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    user_id BIGINT UNSIGNED NOT NULL,
    store_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    role_key VARCHAR(64) NOT NULL DEFAULT 'consultant',
    staff_no VARCHAR(32) NOT NULL DEFAULT '',
    phone VARCHAR(30) NOT NULL DEFAULT '',
    title VARCHAR(60) NOT NULL DEFAULT '',
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_qiling_staff_user_id (user_id),
    KEY idx_qiling_staff_store_id (store_id),
    KEY idx_qiling_staff_role_key (role_key),
    CONSTRAINT fk_qiling_staff_user FOREIGN KEY (user_id) REFERENCES qiling_users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS qiling_customers (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    customer_no VARCHAR(32) NOT NULL,
    store_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    name VARCHAR(80) NOT NULL,
    mobile VARCHAR(30) NOT NULL,
    gender VARCHAR(16) NOT NULL DEFAULT 'unknown',
    birthday DATE NULL,
    source_channel VARCHAR(80) NOT NULL DEFAULT '',
    skin_type VARCHAR(80) NOT NULL DEFAULT '',
    allergies TEXT NULL,
    notes TEXT NULL,
    total_spent DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    visit_count INT NOT NULL DEFAULT 0,
    last_visit_at DATETIME NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_qiling_customers_customer_no (customer_no),
    KEY idx_qiling_customers_mobile (mobile),
    KEY idx_qiling_customers_store_id (store_id),
    KEY idx_qiling_customers_status (status),
    KEY idx_qiling_customers_created_at (created_at),
    KEY idx_qiling_customers_store_created_at (store_id, created_at),
    KEY idx_qiling_customers_store_source_channel (store_id, source_channel)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS qiling_customer_portal_tokens (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    token_hash CHAR(64) NOT NULL,
    token_prefix VARCHAR(16) NOT NULL DEFAULT '',
    customer_id BIGINT UNSIGNED NOT NULL,
    store_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    created_by BIGINT UNSIGNED DEFAULT NULL,
    note VARCHAR(120) NOT NULL DEFAULT '',
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    expire_at DATETIME NULL,
    last_used_at DATETIME NULL,
    use_count INT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_qiling_customer_portal_tokens_hash (token_hash),
    KEY idx_qiling_customer_portal_tokens_customer_id (customer_id),
    KEY idx_qiling_customer_portal_tokens_store_id (store_id),
    KEY idx_qiling_customer_portal_tokens_status (status),
    KEY idx_qiling_customer_portal_tokens_expire_at (expire_at),
    KEY idx_qiling_customer_portal_tokens_customer_status_expire_id (customer_id, status, expire_at, id),
    CONSTRAINT fk_qiling_customer_portal_tokens_customer FOREIGN KEY (customer_id) REFERENCES qiling_customers(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS qiling_customer_portal_ip_guards (
    ip_address VARCHAR(64) NOT NULL,
    fail_count INT NOT NULL DEFAULT 0,
    first_failed_at DATETIME NULL,
    locked_until DATETIME NULL,
    window_started_at DATETIME NULL,
    window_request_count INT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (ip_address),
    KEY idx_qiling_customer_portal_ip_guards_locked_until (locked_until),
    KEY idx_qiling_customer_portal_ip_guards_window_started_at (window_started_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS qiling_customer_tags (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tag_name VARCHAR(80) NOT NULL,
    color VARCHAR(20) NOT NULL DEFAULT '#4f46e5',
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_qiling_customer_tags_tag_name (tag_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS qiling_customer_tag_rel (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    customer_id BIGINT UNSIGNED NOT NULL,
    tag_id BIGINT UNSIGNED NOT NULL,
    created_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_qiling_customer_tag_rel (customer_id, tag_id),
    KEY idx_qiling_customer_tag_rel_tag_id (tag_id),
    CONSTRAINT fk_qiling_customer_tag_rel_customer FOREIGN KEY (customer_id) REFERENCES qiling_customers(id) ON DELETE CASCADE,
    CONSTRAINT fk_qiling_customer_tag_rel_tag FOREIGN KEY (tag_id) REFERENCES qiling_customer_tags(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS qiling_service_categories (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    store_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    category_name VARCHAR(60) NOT NULL,
    sort_order INT NOT NULL DEFAULT 100,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_qiling_service_categories_store_name (store_id, category_name),
    KEY idx_qiling_service_categories_store_id (store_id),
    KEY idx_qiling_service_categories_status (status),
    KEY idx_qiling_service_categories_sort (sort_order, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS qiling_services (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    service_code VARCHAR(32) NOT NULL,
    store_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    service_name VARCHAR(120) NOT NULL,
    category VARCHAR(60) NOT NULL DEFAULT '',
    supports_online_booking TINYINT(1) NOT NULL DEFAULT 0,
    duration_minutes INT NOT NULL DEFAULT 60,
    list_price DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_qiling_services_service_code (service_code),
    KEY idx_qiling_services_store_id (store_id),
    KEY idx_qiling_services_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS qiling_service_packages (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    package_code VARCHAR(32) NOT NULL,
    store_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    package_name VARCHAR(120) NOT NULL,
    service_id BIGINT UNSIGNED NULL,
    total_sessions INT NOT NULL DEFAULT 1,
    sale_price DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    valid_days INT NOT NULL DEFAULT 365,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_qiling_service_packages_package_code (package_code),
    KEY idx_qiling_service_packages_store_id (store_id),
    KEY idx_qiling_service_packages_status (status),
    KEY idx_qiling_service_packages_service_id (service_id),
    CONSTRAINT fk_qiling_service_packages_service FOREIGN KEY (service_id) REFERENCES qiling_services(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS qiling_member_cards (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    card_no VARCHAR(32) NOT NULL,
    customer_id BIGINT UNSIGNED NOT NULL,
    store_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    package_id BIGINT UNSIGNED NOT NULL,
    total_sessions INT NOT NULL DEFAULT 1,
    remaining_sessions INT NOT NULL DEFAULT 1,
    sold_price DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    sold_at DATETIME NOT NULL,
    expire_at DATETIME NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_qiling_member_cards_card_no (card_no),
    KEY idx_qiling_member_cards_customer_id (customer_id),
    KEY idx_qiling_member_cards_store_id (store_id),
    KEY idx_qiling_member_cards_package_id (package_id),
    KEY idx_qiling_member_cards_status (status),
    CONSTRAINT fk_qiling_member_cards_customer FOREIGN KEY (customer_id) REFERENCES qiling_customers(id) ON DELETE CASCADE,
    CONSTRAINT fk_qiling_member_cards_package FOREIGN KEY (package_id) REFERENCES qiling_service_packages(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS qiling_member_card_logs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    member_card_id BIGINT UNSIGNED NOT NULL,
    customer_id BIGINT UNSIGNED NOT NULL,
    action_type VARCHAR(30) NOT NULL,
    delta_sessions INT NOT NULL DEFAULT 0,
    before_sessions INT NOT NULL DEFAULT 0,
    after_sessions INT NOT NULL DEFAULT 0,
    operator_user_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    note VARCHAR(255) NOT NULL DEFAULT '',
    created_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY idx_qiling_member_card_logs_member_card_id (member_card_id),
    KEY idx_qiling_member_card_logs_customer_id (customer_id),
    KEY idx_qiling_member_card_logs_operator_user_id (operator_user_id),
    KEY idx_qiling_member_card_logs_action_type (action_type),
    KEY idx_qiling_member_card_logs_created_at (created_at),
    KEY idx_qiling_member_card_logs_card_created_at (member_card_id, created_at),
    CONSTRAINT fk_qiling_member_card_logs_member_card FOREIGN KEY (member_card_id) REFERENCES qiling_member_cards(id) ON DELETE CASCADE,
    CONSTRAINT fk_qiling_member_card_logs_customer FOREIGN KEY (customer_id) REFERENCES qiling_customers(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS qiling_customer_wallets (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    customer_id BIGINT UNSIGNED NOT NULL,
    balance DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    total_recharge DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    total_gift DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    total_spent DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_qiling_customer_wallets_customer_id (customer_id),
    KEY idx_qiling_customer_wallets_balance (balance),
    CONSTRAINT fk_qiling_customer_wallets_customer FOREIGN KEY (customer_id) REFERENCES qiling_customers(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS qiling_wallet_logs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    customer_id BIGINT UNSIGNED NOT NULL,
    order_id BIGINT UNSIGNED DEFAULT NULL,
    change_type VARCHAR(30) NOT NULL DEFAULT 'adjust',
    delta_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    before_balance DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    after_balance DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    operator_user_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    note VARCHAR(255) NOT NULL DEFAULT '',
    created_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY idx_qiling_wallet_logs_customer_id (customer_id),
    KEY idx_qiling_wallet_logs_order_id (order_id),
    KEY idx_qiling_wallet_logs_change_type (change_type),
    KEY idx_qiling_wallet_logs_created_at (created_at),
    CONSTRAINT fk_qiling_wallet_logs_customer FOREIGN KEY (customer_id) REFERENCES qiling_customers(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS qiling_coupons (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    coupon_code VARCHAR(40) NOT NULL,
    customer_id BIGINT UNSIGNED NOT NULL,
    store_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    coupon_name VARCHAR(120) NOT NULL DEFAULT '',
    coupon_type VARCHAR(20) NOT NULL DEFAULT 'cash',
    face_value DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    min_spend DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    remain_count INT NOT NULL DEFAULT 1,
    expire_at DATETIME NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    source_type VARCHAR(20) NOT NULL DEFAULT 'gift',
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_qiling_coupons_coupon_code (coupon_code),
    KEY idx_qiling_coupons_customer_id (customer_id),
    KEY idx_qiling_coupons_store_id (store_id),
    KEY idx_qiling_coupons_status (status),
    KEY idx_qiling_coupons_expire_at (expire_at),
    KEY idx_qiling_coupons_customer_id_id (customer_id, id),
    CONSTRAINT fk_qiling_coupons_customer FOREIGN KEY (customer_id) REFERENCES qiling_customers(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS qiling_coupon_logs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    coupon_id BIGINT UNSIGNED NOT NULL,
    customer_id BIGINT UNSIGNED NOT NULL,
    order_id BIGINT UNSIGNED DEFAULT NULL,
    action_type VARCHAR(30) NOT NULL DEFAULT 'adjust',
    delta_count INT NOT NULL DEFAULT 0,
    before_count INT NOT NULL DEFAULT 0,
    after_count INT NOT NULL DEFAULT 0,
    operator_user_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    note VARCHAR(255) NOT NULL DEFAULT '',
    created_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY idx_qiling_coupon_logs_coupon_id (coupon_id),
    KEY idx_qiling_coupon_logs_customer_id (customer_id),
    KEY idx_qiling_coupon_logs_order_id (order_id),
    KEY idx_qiling_coupon_logs_action_type (action_type),
    KEY idx_qiling_coupon_logs_created_at (created_at),
    CONSTRAINT fk_qiling_coupon_logs_coupon FOREIGN KEY (coupon_id) REFERENCES qiling_coupons(id) ON DELETE CASCADE,
    CONSTRAINT fk_qiling_coupon_logs_customer FOREIGN KEY (customer_id) REFERENCES qiling_customers(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS qiling_customer_consume_records (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    consume_no VARCHAR(32) NOT NULL,
    customer_id BIGINT UNSIGNED NOT NULL,
    store_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    consume_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    deduct_balance_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    deduct_coupon_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    deduct_member_card_sessions INT NOT NULL DEFAULT 0,
    coupon_usage_json JSON NULL,
    member_card_usage_json JSON NULL,
    note VARCHAR(500) NOT NULL DEFAULT '',
    operator_user_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_qiling_customer_consume_records_consume_no (consume_no),
    KEY idx_qiling_customer_consume_records_customer_id (customer_id),
    KEY idx_qiling_customer_consume_records_store_id (store_id),
    KEY idx_qiling_customer_consume_records_created_at (created_at),
    KEY idx_qiling_customer_consume_records_customer_id_id (customer_id, id),
    CONSTRAINT fk_qiling_customer_consume_records_customer FOREIGN KEY (customer_id) REFERENCES qiling_customers(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS qiling_appointments (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    appointment_no VARCHAR(32) NOT NULL,
    store_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    customer_id BIGINT UNSIGNED NOT NULL,
    staff_id BIGINT UNSIGNED NULL,
    service_id BIGINT UNSIGNED NULL,
    start_at DATETIME NOT NULL,
    end_at DATETIME NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'booked',
    source_channel VARCHAR(60) NOT NULL DEFAULT '',
    notes VARCHAR(500) NOT NULL DEFAULT '',
    created_by BIGINT UNSIGNED NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_qiling_appointments_appointment_no (appointment_no),
    KEY idx_qiling_appointments_store_id (store_id),
    KEY idx_qiling_appointments_customer_id (customer_id),
    KEY idx_qiling_appointments_staff_id (staff_id),
    KEY idx_qiling_appointments_status (status),
    KEY idx_qiling_appointments_start_at (start_at),
    KEY idx_qiling_appointments_store_start_status (store_id, start_at, status),
    KEY idx_qiling_appointments_store_status_id (store_id, status, id),
    KEY idx_qiling_appointments_status_id (status, id),
    CONSTRAINT fk_qiling_appointments_customer FOREIGN KEY (customer_id) REFERENCES qiling_customers(id) ON DELETE CASCADE,
    CONSTRAINT fk_qiling_appointments_staff FOREIGN KEY (staff_id) REFERENCES qiling_staff(id) ON DELETE SET NULL,
    CONSTRAINT fk_qiling_appointments_service FOREIGN KEY (service_id) REFERENCES qiling_services(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS qiling_appointment_consumes (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    appointment_id BIGINT UNSIGNED NOT NULL,
    member_card_id BIGINT UNSIGNED NOT NULL,
    customer_id BIGINT UNSIGNED NOT NULL,
    consume_sessions INT NOT NULL DEFAULT 1,
    before_sessions INT NOT NULL DEFAULT 0,
    after_sessions INT NOT NULL DEFAULT 0,
    operator_user_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    note VARCHAR(255) NOT NULL DEFAULT '',
    rolled_back_at DATETIME NULL,
    rollback_operator_user_id BIGINT UNSIGNED DEFAULT NULL,
    rollback_note VARCHAR(255) NOT NULL DEFAULT '',
    rollback_before_sessions INT NOT NULL DEFAULT 0,
    rollback_after_sessions INT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_qiling_appointment_consumes_appointment_id (appointment_id),
    KEY idx_qiling_appointment_consumes_member_card_id (member_card_id),
    KEY idx_qiling_appointment_consumes_customer_id (customer_id),
    KEY idx_qiling_appointment_consumes_operator_user_id (operator_user_id),
    KEY idx_qiling_appointment_consumes_rolled_back_at (rolled_back_at),
    CONSTRAINT fk_qiling_appointment_consumes_appointment FOREIGN KEY (appointment_id) REFERENCES qiling_appointments(id) ON DELETE CASCADE,
    CONSTRAINT fk_qiling_appointment_consumes_member_card FOREIGN KEY (member_card_id) REFERENCES qiling_member_cards(id) ON DELETE CASCADE,
    CONSTRAINT fk_qiling_appointment_consumes_customer FOREIGN KEY (customer_id) REFERENCES qiling_customers(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS qiling_orders (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    order_no VARCHAR(32) NOT NULL,
    store_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    customer_id BIGINT UNSIGNED NOT NULL,
    appointment_id BIGINT UNSIGNED DEFAULT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'unpaid',
    subtotal_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    discount_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    coupon_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    payable_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    paid_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    paid_at DATETIME NULL,
    note VARCHAR(500) NOT NULL DEFAULT '',
    created_by BIGINT UNSIGNED NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_qiling_orders_order_no (order_no),
    KEY idx_qiling_orders_store_id (store_id),
    KEY idx_qiling_orders_customer_id (customer_id),
    KEY idx_qiling_orders_appointment_id (appointment_id),
    KEY idx_qiling_orders_status (status),
    KEY idx_qiling_orders_paid_at (paid_at),
    KEY idx_qiling_orders_status_paid_at_store (status, paid_at, store_id),
    KEY idx_qiling_orders_store_paid_at_customer (store_id, paid_at, customer_id),
    KEY idx_qiling_orders_store_status_id (store_id, status, id),
    KEY idx_qiling_orders_customer_id_id (customer_id, id),
    CONSTRAINT fk_qiling_orders_customer FOREIGN KEY (customer_id) REFERENCES qiling_customers(id) ON DELETE CASCADE,
    CONSTRAINT fk_qiling_orders_appointment FOREIGN KEY (appointment_id) REFERENCES qiling_appointments(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS qiling_order_items (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    order_id BIGINT UNSIGNED NOT NULL,
    store_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    customer_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    item_type VARCHAR(30) NOT NULL DEFAULT 'custom',
    item_ref_id BIGINT UNSIGNED DEFAULT NULL,
    item_name VARCHAR(120) NOT NULL DEFAULT '',
    qty INT NOT NULL DEFAULT 1,
    unit_price DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    line_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    discount_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    final_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    staff_id BIGINT UNSIGNED DEFAULT NULL,
    commission_rate DECIMAL(5,2) NOT NULL DEFAULT 0.00,
    commission_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    note VARCHAR(255) NOT NULL DEFAULT '',
    created_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY idx_qiling_order_items_order_id (order_id),
    KEY idx_qiling_order_items_store_id (store_id),
    KEY idx_qiling_order_items_customer_id (customer_id),
    KEY idx_qiling_order_items_item_type (item_type),
    KEY idx_qiling_order_items_item_ref_id (item_ref_id),
    KEY idx_qiling_order_items_staff_id (staff_id),
    KEY idx_qiling_order_items_order_item (order_id, item_type, item_ref_id),
    KEY idx_qiling_order_items_staff_order (staff_id, order_id),
    CONSTRAINT fk_qiling_order_items_order FOREIGN KEY (order_id) REFERENCES qiling_orders(id) ON DELETE CASCADE,
    CONSTRAINT fk_qiling_order_items_staff FOREIGN KEY (staff_id) REFERENCES qiling_staff(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS qiling_order_payments (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    order_id BIGINT UNSIGNED NOT NULL,
    payment_no VARCHAR(32) NOT NULL,
    pay_method VARCHAR(30) NOT NULL DEFAULT 'cash',
    amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    status VARCHAR(20) NOT NULL DEFAULT 'paid',
    paid_at DATETIME NOT NULL,
    operator_user_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    note VARCHAR(255) NOT NULL DEFAULT '',
    created_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_qiling_order_payments_payment_no (payment_no),
    KEY idx_qiling_order_payments_order_id (order_id),
    KEY idx_qiling_order_payments_pay_method (pay_method),
    KEY idx_qiling_order_payments_paid_at (paid_at),
    KEY idx_qiling_order_payments_status_paid_at (status, paid_at),
    KEY idx_qiling_order_payments_paid_at_order_id (paid_at, order_id),
    KEY idx_qiling_order_payments_pay_method_status_paid_at (pay_method, status, paid_at),
    CONSTRAINT fk_qiling_order_payments_order FOREIGN KEY (order_id) REFERENCES qiling_orders(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS qiling_online_payments (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    order_id BIGINT UNSIGNED NOT NULL,
    payment_no VARCHAR(40) NOT NULL,
    out_trade_no VARCHAR(40) NOT NULL,
    channel VARCHAR(20) NOT NULL DEFAULT '',
    scene VARCHAR(20) NOT NULL DEFAULT '',
    amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    currency VARCHAR(8) NOT NULL DEFAULT 'CNY',
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    gateway_trade_no VARCHAR(100) NOT NULL DEFAULT '',
    openid VARCHAR(64) NOT NULL DEFAULT '',
    client_ip VARCHAR(64) NOT NULL DEFAULT '',
    qr_code TEXT NULL,
    pay_url TEXT NULL,
    prepay_id VARCHAR(128) NOT NULL DEFAULT '',
    gateway_response_json JSON NULL,
    notify_payload_json JSON NULL,
    paid_at DATETIME NULL,
    expire_at DATETIME NULL,
    created_by BIGINT UNSIGNED NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_qiling_online_payments_payment_no (payment_no),
    UNIQUE KEY uq_qiling_online_payments_out_trade_no (out_trade_no),
    KEY idx_qiling_online_payments_order_id (order_id),
    KEY idx_qiling_online_payments_status (status),
    KEY idx_qiling_online_payments_channel (channel),
    KEY idx_qiling_online_payments_created_at (created_at),
    KEY idx_qiling_online_payments_order_status_id (order_id, status, id),
    CONSTRAINT fk_qiling_online_payments_order FOREIGN KEY (order_id) REFERENCES qiling_orders(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS qiling_online_payment_refunds (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    online_payment_id BIGINT UNSIGNED NOT NULL,
    order_id BIGINT UNSIGNED NOT NULL,
    refund_no VARCHAR(40) NOT NULL,
    out_refund_no VARCHAR(40) NOT NULL,
    channel VARCHAR(20) NOT NULL DEFAULT '',
    refund_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    gateway_refund_no VARCHAR(100) NOT NULL DEFAULT '',
    reason VARCHAR(255) NOT NULL DEFAULT '',
    gateway_response_json JSON NULL,
    notify_payload_json JSON NULL,
    refunded_at DATETIME NULL,
    created_by BIGINT UNSIGNED NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_qiling_online_payment_refunds_refund_no (refund_no),
    UNIQUE KEY uq_qiling_online_payment_refunds_out_refund_no (out_refund_no),
    KEY idx_qiling_online_payment_refunds_online_payment_id (online_payment_id),
    KEY idx_qiling_online_payment_refunds_order_id (order_id),
    KEY idx_qiling_online_payment_refunds_status (status),
    KEY idx_qiling_online_payment_refunds_channel (channel),
    CONSTRAINT fk_qiling_online_payment_refunds_online_payment FOREIGN KEY (online_payment_id) REFERENCES qiling_online_payments(id) ON DELETE CASCADE,
    CONSTRAINT fk_qiling_online_payment_refunds_order FOREIGN KEY (order_id) REFERENCES qiling_orders(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS qiling_finance_daily_settlements (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    settlement_date DATE NOT NULL,
    store_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    cash_in_amount DECIMAL(14,2) NOT NULL DEFAULT 0.00,
    refund_out_amount DECIMAL(14,2) NOT NULL DEFAULT 0.00,
    net_amount DECIMAL(14,2) NOT NULL DEFAULT 0.00,
    online_in_amount DECIMAL(14,2) NOT NULL DEFAULT 0.00,
    offline_in_amount DECIMAL(14,2) NOT NULL DEFAULT 0.00,
    channel_diff_amount DECIMAL(14,2) NOT NULL DEFAULT 0.00,
    payment_count INT NOT NULL DEFAULT 0,
    refund_count INT NOT NULL DEFAULT 0,
    exception_count INT NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL DEFAULT 'open',
    note VARCHAR(500) NOT NULL DEFAULT '',
    closed_by BIGINT UNSIGNED DEFAULT NULL,
    closed_at DATETIME NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_qiling_finance_daily_settlements_store_date (store_id, settlement_date),
    KEY idx_qiling_finance_daily_settlements_store_status_date (store_id, status, settlement_date),
    KEY idx_qiling_finance_daily_settlements_closed_at (closed_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS qiling_finance_reconciliation_items (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    settlement_date DATE NOT NULL,
    store_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    channel VARCHAR(30) NOT NULL DEFAULT '',
    ledger_amount DECIMAL(14,2) NOT NULL DEFAULT 0.00,
    gateway_amount DECIMAL(14,2) NOT NULL DEFAULT 0.00,
    diff_amount DECIMAL(14,2) NOT NULL DEFAULT 0.00,
    payment_count INT NOT NULL DEFAULT 0,
    refund_count INT NOT NULL DEFAULT 0,
    exception_count INT NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_qiling_finance_reconciliation_items_dim (settlement_date, store_id, channel),
    KEY idx_qiling_finance_reconciliation_items_store_date (store_id, settlement_date),
    KEY idx_qiling_finance_reconciliation_items_store_diff (store_id, diff_amount, settlement_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS qiling_finance_exceptions (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    settlement_date DATE NOT NULL,
    store_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    channel VARCHAR(30) NOT NULL DEFAULT '',
    exception_type VARCHAR(30) NOT NULL DEFAULT 'manual',
    order_id BIGINT UNSIGNED DEFAULT NULL,
    payment_no VARCHAR(40) NOT NULL DEFAULT '',
    refund_no VARCHAR(40) NOT NULL DEFAULT '',
    amount DECIMAL(14,2) NOT NULL DEFAULT 0.00,
    detail VARCHAR(500) NOT NULL DEFAULT '',
    status VARCHAR(20) NOT NULL DEFAULT 'open',
    resolved_by BIGINT UNSIGNED DEFAULT NULL,
    resolved_at DATETIME NULL,
    resolution_note VARCHAR(500) NOT NULL DEFAULT '',
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_qiling_finance_exceptions_auto_order_channel (settlement_date, store_id, channel, exception_type, order_id),
    KEY idx_qiling_finance_exceptions_store_status_date (store_id, status, settlement_date, id),
    KEY idx_qiling_finance_exceptions_order_id (order_id),
    KEY idx_qiling_finance_exceptions_payment_no (payment_no),
    KEY idx_qiling_finance_exceptions_refund_no (refund_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS qiling_inventory_materials (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    store_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    material_code VARCHAR(40) NOT NULL,
    material_name VARCHAR(150) NOT NULL,
    category VARCHAR(60) NOT NULL DEFAULT '',
    unit VARCHAR(20) NOT NULL DEFAULT '个',
    safety_stock DECIMAL(14,3) NOT NULL DEFAULT 0.000,
    current_stock DECIMAL(14,3) NOT NULL DEFAULT 0.000,
    avg_cost DECIMAL(12,4) NOT NULL DEFAULT 0.0000,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    note VARCHAR(500) NOT NULL DEFAULT '',
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_qiling_inventory_materials_store_code (store_id, material_code),
    KEY idx_qiling_inventory_materials_store_status_name (store_id, status, material_name),
    KEY idx_qiling_inventory_materials_store_low_stock (store_id, status, current_stock, safety_stock)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS qiling_inventory_service_materials (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    store_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    service_id BIGINT UNSIGNED NOT NULL,
    material_id BIGINT UNSIGNED NOT NULL,
    consume_qty DECIMAL(14,3) NOT NULL DEFAULT 1.000,
    wastage_rate DECIMAL(5,2) NOT NULL DEFAULT 0.00,
    enabled TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_qiling_inventory_service_materials_dim (store_id, service_id, material_id),
    KEY idx_qiling_inventory_service_materials_service_enabled (service_id, enabled),
    KEY idx_qiling_inventory_service_materials_material_enabled (material_id, enabled),
    CONSTRAINT fk_qiling_inventory_service_materials_service FOREIGN KEY (service_id) REFERENCES qiling_services(id) ON DELETE CASCADE,
    CONSTRAINT fk_qiling_inventory_service_materials_material FOREIGN KEY (material_id) REFERENCES qiling_inventory_materials(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS qiling_inventory_stock_movements (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    store_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    material_id BIGINT UNSIGNED NOT NULL,
    movement_type VARCHAR(30) NOT NULL DEFAULT 'adjust',
    qty_delta DECIMAL(14,3) NOT NULL DEFAULT 0.000,
    qty_before DECIMAL(14,3) NOT NULL DEFAULT 0.000,
    qty_after DECIMAL(14,3) NOT NULL DEFAULT 0.000,
    unit_cost DECIMAL(12,4) NOT NULL DEFAULT 0.0000,
    total_cost DECIMAL(14,2) NOT NULL DEFAULT 0.00,
    reference_type VARCHAR(30) NOT NULL DEFAULT '',
    reference_id BIGINT UNSIGNED DEFAULT NULL,
    note VARCHAR(500) NOT NULL DEFAULT '',
    operator_user_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY idx_qiling_inventory_stock_movements_material_created (material_id, created_at, id),
    KEY idx_qiling_inventory_stock_movements_store_type_created (store_id, movement_type, created_at, id),
    KEY idx_qiling_inventory_stock_movements_reference (reference_type, reference_id),
    KEY idx_qiling_inventory_stock_movements_created_at (created_at),
    CONSTRAINT fk_qiling_inventory_stock_movements_material FOREIGN KEY (material_id) REFERENCES qiling_inventory_materials(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS qiling_inventory_purchase_orders (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    store_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    purchase_no VARCHAR(40) NOT NULL,
    supplier_name VARCHAR(120) NOT NULL DEFAULT '',
    status VARCHAR(20) NOT NULL DEFAULT 'draft',
    total_amount DECIMAL(14,2) NOT NULL DEFAULT 0.00,
    expected_at DATETIME NULL,
    received_at DATETIME NULL,
    note VARCHAR(500) NOT NULL DEFAULT '',
    created_by BIGINT UNSIGNED NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_qiling_inventory_purchase_orders_purchase_no (purchase_no),
    KEY idx_qiling_inventory_purchase_orders_store_status_created (store_id, status, created_at),
    KEY idx_qiling_inventory_purchase_orders_expected_at (expected_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS qiling_inventory_purchase_items (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    purchase_id BIGINT UNSIGNED NOT NULL,
    material_id BIGINT UNSIGNED NOT NULL,
    qty DECIMAL(14,3) NOT NULL DEFAULT 0.000,
    received_qty DECIMAL(14,3) NOT NULL DEFAULT 0.000,
    unit_cost DECIMAL(12,4) NOT NULL DEFAULT 0.0000,
    line_amount DECIMAL(14,2) NOT NULL DEFAULT 0.00,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY idx_qiling_inventory_purchase_items_purchase_id (purchase_id),
    KEY idx_qiling_inventory_purchase_items_material_id (material_id),
    CONSTRAINT fk_qiling_inventory_purchase_items_purchase FOREIGN KEY (purchase_id) REFERENCES qiling_inventory_purchase_orders(id) ON DELETE CASCADE,
    CONSTRAINT fk_qiling_inventory_purchase_items_material FOREIGN KEY (material_id) REFERENCES qiling_inventory_materials(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS qiling_commission_rules (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    store_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    rule_name VARCHAR(120) NOT NULL DEFAULT '',
    target_type VARCHAR(30) NOT NULL DEFAULT 'all',
    target_ref_id BIGINT UNSIGNED DEFAULT NULL,
    staff_role_key VARCHAR(64) NOT NULL DEFAULT '',
    rate_percent DECIMAL(5,2) NOT NULL DEFAULT 0.00,
    enabled TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY idx_qiling_commission_rules_store_id (store_id),
    KEY idx_qiling_commission_rules_enabled (enabled),
    KEY idx_qiling_commission_rules_target_type (target_type),
    KEY idx_qiling_commission_rules_target_ref_id (target_ref_id),
    KEY idx_qiling_commission_rules_staff_role_key (staff_role_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS qiling_followup_plans (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    store_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    trigger_type VARCHAR(50) NOT NULL DEFAULT 'appointment_completed',
    plan_name VARCHAR(100) NOT NULL DEFAULT '',
    schedule_days_json JSON NULL,
    enabled TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_qiling_followup_plans_store_trigger (store_id, trigger_type),
    KEY idx_qiling_followup_plans_enabled (enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS qiling_followup_tasks (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    plan_id BIGINT UNSIGNED DEFAULT NULL,
    appointment_id BIGINT UNSIGNED NOT NULL,
    customer_id BIGINT UNSIGNED NOT NULL,
    store_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    schedule_day INT NOT NULL DEFAULT 1,
    due_at DATETIME NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    notify_status VARCHAR(20) NOT NULL DEFAULT 'pending',
    notified_at DATETIME NULL,
    notify_channel_id BIGINT UNSIGNED DEFAULT NULL,
    notify_error VARCHAR(500) NOT NULL DEFAULT '',
    assigned_staff_id BIGINT UNSIGNED DEFAULT NULL,
    title VARCHAR(200) NOT NULL DEFAULT '',
    content VARCHAR(1000) NOT NULL DEFAULT '',
    result_note VARCHAR(1000) NOT NULL DEFAULT '',
    completed_at DATETIME NULL,
    completed_by BIGINT UNSIGNED DEFAULT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_qiling_followup_tasks_appointment_day (appointment_id, schedule_day),
    KEY idx_qiling_followup_tasks_plan_id (plan_id),
    KEY idx_qiling_followup_tasks_customer_id (customer_id),
    KEY idx_qiling_followup_tasks_store_id (store_id),
    KEY idx_qiling_followup_tasks_status (status),
    KEY idx_qiling_followup_tasks_notify_status (notify_status),
    KEY idx_qiling_followup_tasks_notify_channel_id (notify_channel_id),
    KEY idx_qiling_followup_tasks_due_at (due_at),
    KEY idx_qiling_followup_tasks_store_status_due_id (store_id, status, due_at, id),
    KEY idx_qiling_followup_tasks_status_notify_due_id (status, notify_status, due_at, id),
    KEY idx_qiling_followup_tasks_appointment_status (appointment_id, status),
    CONSTRAINT fk_qiling_followup_tasks_plan FOREIGN KEY (plan_id) REFERENCES qiling_followup_plans(id) ON DELETE SET NULL,
    CONSTRAINT fk_qiling_followup_tasks_appointment FOREIGN KEY (appointment_id) REFERENCES qiling_appointments(id) ON DELETE CASCADE,
    CONSTRAINT fk_qiling_followup_tasks_customer FOREIGN KEY (customer_id) REFERENCES qiling_customers(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS qiling_report_daily_store (
    report_date DATE NOT NULL,
    store_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    paid_amount DECIMAL(14,2) NOT NULL DEFAULT 0.00,
    refund_amount DECIMAL(14,2) NOT NULL DEFAULT 0.00,
    paid_orders INT NOT NULL DEFAULT 0,
    refund_orders INT NOT NULL DEFAULT 0,
    paid_txn_count INT NOT NULL DEFAULT 0,
    refund_txn_count INT NOT NULL DEFAULT 0,
    paid_customers INT NOT NULL DEFAULT 0,
    new_customers INT NOT NULL DEFAULT 0,
    appointments_total INT NOT NULL DEFAULT 0,
    appointments_completed INT NOT NULL DEFAULT 0,
    appointments_cancelled INT NOT NULL DEFAULT 0,
    appointments_no_show INT NOT NULL DEFAULT 0,
    card_consumed_sessions INT NOT NULL DEFAULT 0,
    aggregated_at DATETIME NOT NULL,
    PRIMARY KEY (report_date, store_id),
    KEY idx_qiling_report_daily_store_store_date (store_id, report_date),
    KEY idx_qiling_report_daily_store_aggregated_at (aggregated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS qiling_report_daily_channel (
    report_date DATE NOT NULL,
    store_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    source_channel VARCHAR(80) NOT NULL DEFAULT '',
    new_customers INT NOT NULL DEFAULT 0,
    paid_customers INT NOT NULL DEFAULT 0,
    paid_orders INT NOT NULL DEFAULT 0,
    paid_amount DECIMAL(14,2) NOT NULL DEFAULT 0.00,
    refund_amount DECIMAL(14,2) NOT NULL DEFAULT 0.00,
    aggregated_at DATETIME NOT NULL,
    PRIMARY KEY (report_date, store_id, source_channel),
    KEY idx_qiling_report_daily_channel_store_date (store_id, report_date),
    KEY idx_qiling_report_daily_channel_channel (source_channel)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS qiling_report_daily_channel_cost (
    report_date DATE NOT NULL,
    store_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    source_channel VARCHAR(80) NOT NULL DEFAULT '',
    cost_amount DECIMAL(14,2) NOT NULL DEFAULT 0.00,
    note VARCHAR(255) NOT NULL DEFAULT '',
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (report_date, store_id, source_channel),
    KEY idx_qiling_report_daily_channel_cost_store_date (store_id, report_date),
    KEY idx_qiling_report_daily_channel_cost_channel (source_channel)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS qiling_report_daily_service (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    report_date DATE NOT NULL,
    store_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    item_type VARCHAR(30) NOT NULL DEFAULT 'custom',
    item_ref_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    item_name VARCHAR(120) NOT NULL DEFAULT '',
    total_qty INT NOT NULL DEFAULT 0,
    item_lines INT NOT NULL DEFAULT 0,
    order_count INT NOT NULL DEFAULT 0,
    sales_amount DECIMAL(14,2) NOT NULL DEFAULT 0.00,
    commission_amount DECIMAL(14,2) NOT NULL DEFAULT 0.00,
    aggregated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_qiling_report_daily_service_dim (report_date, store_id, item_type, item_ref_id, item_name),
    KEY idx_qiling_report_daily_service_store_date (store_id, report_date),
    KEY idx_qiling_report_daily_service_sales (sales_amount)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS qiling_report_aggregate_marks (
    report_date DATE NOT NULL,
    store_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    aggregated_at DATETIME NOT NULL,
    PRIMARY KEY (report_date, store_id),
    KEY idx_qiling_report_aggregate_marks_aggregated_at (aggregated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS qiling_crm_pipelines (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    pipeline_key VARCHAR(40) NOT NULL,
    pipeline_name VARCHAR(100) NOT NULL,
    stages_json JSON NULL,
    is_system TINYINT(1) NOT NULL DEFAULT 1,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_qiling_crm_pipelines_key (pipeline_key),
    KEY idx_qiling_crm_pipelines_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS qiling_crm_companies (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    company_name VARCHAR(150) NOT NULL,
    company_type VARCHAR(30) NOT NULL DEFAULT 'enterprise',
    country_code VARCHAR(8) NOT NULL DEFAULT '',
    website VARCHAR(255) NOT NULL DEFAULT '',
    industry VARCHAR(80) NOT NULL DEFAULT '',
    source_channel VARCHAR(80) NOT NULL DEFAULT '',
    owner_user_id BIGINT UNSIGNED DEFAULT NULL,
    owner_team_id BIGINT UNSIGNED DEFAULT NULL,
    owner_department_id BIGINT UNSIGNED DEFAULT NULL,
    visibility_level VARCHAR(20) NOT NULL DEFAULT 'private',
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    is_archived TINYINT(1) NOT NULL DEFAULT 0,
    archived_at DATETIME NULL,
    archived_by BIGINT UNSIGNED DEFAULT NULL,
    deleted_at DATETIME NULL,
    deleted_by BIGINT UNSIGNED DEFAULT NULL,
    tags_json JSON NULL,
    extra_json JSON NULL,
    created_by BIGINT UNSIGNED DEFAULT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY idx_qiling_crm_companies_owner_status (owner_user_id, status, id),
    KEY idx_qiling_crm_companies_visibility_owner_team (visibility_level, owner_team_id, owner_user_id, id),
    KEY idx_qiling_crm_companies_visibility_owner_dept (visibility_level, owner_department_id, owner_user_id, id),
    KEY idx_qiling_crm_companies_status_id (status, id),
    KEY idx_qiling_crm_companies_country (country_code),
    KEY idx_qiling_crm_companies_type (company_type),
    KEY idx_qiling_crm_companies_created_at (created_at),
    KEY idx_qiling_crm_companies_company_name (company_name),
    KEY idx_qiling_crm_companies_created_by_id (created_by, id),
    KEY idx_qiling_crm_companies_company_deleted_id (company_name, deleted_at, id),
    KEY idx_qiling_crm_companies_owner_deleted_archived_id (owner_user_id, deleted_at, is_archived, id),
    FULLTEXT KEY ft_qiling_crm_companies_search (company_name, website, industry),
    KEY idx_qiling_crm_companies_deleted_archived (deleted_at, is_archived, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS qiling_crm_contacts (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    company_id BIGINT UNSIGNED DEFAULT NULL,
    contact_name VARCHAR(100) NOT NULL,
    mobile VARCHAR(30) NOT NULL DEFAULT '',
    email VARCHAR(120) NOT NULL DEFAULT '',
    wechat VARCHAR(80) NOT NULL DEFAULT '',
    whatsapp VARCHAR(80) NOT NULL DEFAULT '',
    title VARCHAR(80) NOT NULL DEFAULT '',
    country_code VARCHAR(8) NOT NULL DEFAULT '',
    language_code VARCHAR(16) NOT NULL DEFAULT '',
    source_channel VARCHAR(80) NOT NULL DEFAULT '',
    owner_user_id BIGINT UNSIGNED DEFAULT NULL,
    owner_team_id BIGINT UNSIGNED DEFAULT NULL,
    owner_department_id BIGINT UNSIGNED DEFAULT NULL,
    visibility_level VARCHAR(20) NOT NULL DEFAULT 'private',
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    is_archived TINYINT(1) NOT NULL DEFAULT 0,
    archived_at DATETIME NULL,
    archived_by BIGINT UNSIGNED DEFAULT NULL,
    deleted_at DATETIME NULL,
    deleted_by BIGINT UNSIGNED DEFAULT NULL,
    tags_json JSON NULL,
    extra_json JSON NULL,
    created_by BIGINT UNSIGNED DEFAULT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY idx_qiling_crm_contacts_company (company_id),
    KEY idx_qiling_crm_contacts_owner_status (owner_user_id, status, id),
    KEY idx_qiling_crm_contacts_visibility_owner_team (visibility_level, owner_team_id, owner_user_id, id),
    KEY idx_qiling_crm_contacts_visibility_owner_dept (visibility_level, owner_department_id, owner_user_id, id),
    KEY idx_qiling_crm_contacts_status_id (status, id),
    KEY idx_qiling_crm_contacts_mobile (mobile),
    KEY idx_qiling_crm_contacts_email (email),
    KEY idx_qiling_crm_contacts_whatsapp (whatsapp),
    KEY idx_qiling_crm_contacts_created_at (created_at),
    KEY idx_qiling_crm_contacts_created_by_id (created_by, id),
    KEY idx_qiling_crm_contacts_mobile_deleted_id (mobile, deleted_at, id),
    KEY idx_qiling_crm_contacts_email_deleted_id (email, deleted_at, id),
    KEY idx_qiling_crm_contacts_whatsapp_deleted_id (whatsapp, deleted_at, id),
    KEY idx_qiling_crm_contacts_owner_deleted_archived_id (owner_user_id, deleted_at, is_archived, id),
    KEY idx_qiling_crm_contacts_company_deleted_archived_id (company_id, deleted_at, is_archived, id),
    FULLTEXT KEY ft_qiling_crm_contacts_search (contact_name, mobile, email, whatsapp),
    KEY idx_qiling_crm_contacts_deleted_archived (deleted_at, is_archived, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS qiling_crm_leads (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    lead_name VARCHAR(120) NOT NULL,
    mobile VARCHAR(30) NOT NULL DEFAULT '',
    email VARCHAR(120) NOT NULL DEFAULT '',
    company_name VARCHAR(150) NOT NULL DEFAULT '',
    country_code VARCHAR(8) NOT NULL DEFAULT '',
    language_code VARCHAR(16) NOT NULL DEFAULT '',
    source_channel VARCHAR(80) NOT NULL DEFAULT '',
    intent_level VARCHAR(20) NOT NULL DEFAULT 'warm',
    status VARCHAR(20) NOT NULL DEFAULT 'new',
    visibility_scope VARCHAR(20) NOT NULL DEFAULT 'private',
    public_pool_at DATETIME NULL,
    owner_user_id BIGINT UNSIGNED DEFAULT NULL,
    owner_team_id BIGINT UNSIGNED DEFAULT NULL,
    owner_department_id BIGINT UNSIGNED DEFAULT NULL,
    visibility_level VARCHAR(20) NOT NULL DEFAULT 'private',
    related_company_id BIGINT UNSIGNED DEFAULT NULL,
    related_contact_id BIGINT UNSIGNED DEFAULT NULL,
    next_followup_at DATETIME NULL,
    last_contact_at DATETIME NULL,
    is_archived TINYINT(1) NOT NULL DEFAULT 0,
    archived_at DATETIME NULL,
    archived_by BIGINT UNSIGNED DEFAULT NULL,
    deleted_at DATETIME NULL,
    deleted_by BIGINT UNSIGNED DEFAULT NULL,
    tags_json JSON NULL,
    extra_json JSON NULL,
    created_by BIGINT UNSIGNED DEFAULT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY idx_qiling_crm_leads_owner_status (owner_user_id, status, id),
    KEY idx_qiling_crm_leads_visibility_owner_team (visibility_level, owner_team_id, owner_user_id, id),
    KEY idx_qiling_crm_leads_visibility_owner_dept (visibility_level, owner_department_id, owner_user_id, id),
    KEY idx_qiling_crm_leads_status_id (status, id),
    KEY idx_qiling_crm_leads_owner_intent_id (owner_user_id, intent_level, id),
    KEY idx_qiling_crm_leads_next_followup (next_followup_at, status),
    KEY idx_qiling_crm_leads_mobile (mobile),
    KEY idx_qiling_crm_leads_email (email),
    KEY idx_qiling_crm_leads_company (related_company_id),
    KEY idx_qiling_crm_leads_contact (related_contact_id),
    KEY idx_qiling_crm_leads_visibility_owner (visibility_scope, owner_user_id, id),
    KEY idx_qiling_crm_leads_public_pool (visibility_scope, public_pool_at, id),
    KEY idx_qiling_crm_leads_created_by_id (created_by, id),
    KEY idx_qiling_crm_leads_company_name_deleted_id (company_name, deleted_at, id),
    KEY idx_qiling_crm_leads_mobile_deleted_id (mobile, deleted_at, id),
    KEY idx_qiling_crm_leads_email_deleted_id (email, deleted_at, id),
    KEY idx_qiling_crm_leads_owner_deleted_archived_id (owner_user_id, deleted_at, is_archived, id),
    KEY idx_qiling_crm_leads_created_deleted_archived_id (created_by, deleted_at, is_archived, id),
    KEY idx_qiling_crm_leads_visibility_deleted_archived_pool (visibility_scope, deleted_at, is_archived, public_pool_at, id),
    FULLTEXT KEY ft_qiling_crm_leads_search (lead_name, mobile, email, company_name),
    KEY idx_qiling_crm_leads_deleted_archived (deleted_at, is_archived, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS qiling_crm_deals (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    deal_name VARCHAR(150) NOT NULL,
    company_id BIGINT UNSIGNED DEFAULT NULL,
    contact_id BIGINT UNSIGNED DEFAULT NULL,
    lead_id BIGINT UNSIGNED DEFAULT NULL,
    pipeline_key VARCHAR(40) NOT NULL DEFAULT 'default',
    stage_key VARCHAR(40) NOT NULL DEFAULT 'new',
    deal_status VARCHAR(20) NOT NULL DEFAULT 'open',
    currency_code VARCHAR(8) NOT NULL DEFAULT 'CNY',
    amount DECIMAL(14,2) NOT NULL DEFAULT 0.00,
    expected_close_date DATE NULL,
    won_at DATETIME NULL,
    lost_reason VARCHAR(255) NOT NULL DEFAULT '',
    source_channel VARCHAR(80) NOT NULL DEFAULT '',
    owner_user_id BIGINT UNSIGNED DEFAULT NULL,
    owner_team_id BIGINT UNSIGNED DEFAULT NULL,
    owner_department_id BIGINT UNSIGNED DEFAULT NULL,
    visibility_level VARCHAR(20) NOT NULL DEFAULT 'private',
    extra_json JSON NULL,
    created_by BIGINT UNSIGNED DEFAULT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY idx_qiling_crm_deals_owner_status (owner_user_id, deal_status, id),
    KEY idx_qiling_crm_deals_visibility_owner_team (visibility_level, owner_team_id, owner_user_id, id),
    KEY idx_qiling_crm_deals_visibility_owner_dept (visibility_level, owner_department_id, owner_user_id, id),
    KEY idx_qiling_crm_deals_status_id (deal_status, id),
    KEY idx_qiling_crm_deals_pipeline_stage (pipeline_key, stage_key),
    KEY idx_qiling_crm_deals_pipeline_stage_id (pipeline_key, stage_key, id),
    KEY idx_qiling_crm_deals_expected_close (expected_close_date),
    KEY idx_qiling_crm_deals_owner_id (owner_user_id, id),
    KEY idx_qiling_crm_deals_company (company_id),
    KEY idx_qiling_crm_deals_contact (contact_id),
    KEY idx_qiling_crm_deals_lead (lead_id),
    KEY idx_qiling_crm_deals_created_by_id (created_by, id),
    FULLTEXT KEY ft_qiling_crm_deals_name (deal_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS qiling_crm_activities (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    entity_type VARCHAR(30) NOT NULL,
    entity_id BIGINT UNSIGNED NOT NULL,
    activity_type VARCHAR(30) NOT NULL DEFAULT 'note',
    subject VARCHAR(150) NOT NULL DEFAULT '',
    content TEXT NULL,
    due_at DATETIME NULL,
    done_at DATETIME NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'todo',
    owner_user_id BIGINT UNSIGNED DEFAULT NULL,
    owner_team_id BIGINT UNSIGNED DEFAULT NULL,
    owner_department_id BIGINT UNSIGNED DEFAULT NULL,
    visibility_level VARCHAR(20) NOT NULL DEFAULT 'private',
    created_by BIGINT UNSIGNED DEFAULT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY idx_qiling_crm_activities_entity (entity_type, entity_id, id),
    KEY idx_qiling_crm_activities_owner_status_due (owner_user_id, status, due_at, id),
    KEY idx_qiling_crm_activities_visibility_owner_team (visibility_level, owner_team_id, owner_user_id, id),
    KEY idx_qiling_crm_activities_visibility_owner_dept (visibility_level, owner_department_id, owner_user_id, id),
    KEY idx_qiling_crm_activities_status_due_id (status, due_at, id),
    KEY idx_qiling_crm_activities_owner_id (owner_user_id, id),
    KEY idx_qiling_crm_activities_created_by_id (created_by, id),
    KEY idx_qiling_crm_activities_due_status (due_at, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS qiling_crm_transfer_logs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    entity_type VARCHAR(20) NOT NULL DEFAULT 'lead',
    entity_id BIGINT UNSIGNED NOT NULL,
    action_type VARCHAR(30) NOT NULL DEFAULT 'transfer',
    from_owner_user_id BIGINT UNSIGNED DEFAULT NULL,
    to_owner_user_id BIGINT UNSIGNED DEFAULT NULL,
    note VARCHAR(255) NOT NULL DEFAULT '',
    created_by BIGINT UNSIGNED NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY idx_qiling_crm_transfer_logs_entity (entity_type, entity_id, id),
    KEY idx_qiling_crm_transfer_logs_entity_type_id (entity_type, id),
    KEY idx_qiling_crm_transfer_logs_to_owner (to_owner_user_id, id),
    KEY idx_qiling_crm_transfer_logs_from_owner (from_owner_user_id, id),
    KEY idx_qiling_crm_transfer_logs_created_by (created_by, id),
    KEY idx_qiling_crm_transfer_logs_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS qiling_crm_assignment_rules (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    rule_name VARCHAR(120) NOT NULL,
    entity_type VARCHAR(20) NOT NULL DEFAULT 'lead',
    source_scope VARCHAR(20) NOT NULL DEFAULT 'public_pool',
    strategy VARCHAR(20) NOT NULL DEFAULT 'round_robin',
    member_user_ids_json JSON NULL,
    enabled TINYINT(1) NOT NULL DEFAULT 1,
    last_pick_index INT NOT NULL DEFAULT -1,
    created_by BIGINT UNSIGNED NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY idx_qiling_crm_assignment_rules_entity_enabled (entity_type, enabled, id),
    KEY idx_qiling_crm_assignment_rules_source_scope (source_scope, enabled, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS qiling_crm_departments (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    department_name VARCHAR(120) NOT NULL,
    parent_id BIGINT UNSIGNED DEFAULT NULL,
    manager_user_id BIGINT UNSIGNED DEFAULT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    created_by BIGINT UNSIGNED DEFAULT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_qiling_crm_departments_name (department_name),
    KEY idx_qiling_crm_departments_parent_id (parent_id),
    KEY idx_qiling_crm_departments_manager_user_id (manager_user_id),
    KEY idx_qiling_crm_departments_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS qiling_crm_teams (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    team_name VARCHAR(120) NOT NULL,
    department_id BIGINT UNSIGNED DEFAULT NULL,
    leader_user_id BIGINT UNSIGNED DEFAULT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    created_by BIGINT UNSIGNED DEFAULT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_qiling_crm_teams_name (team_name),
    KEY idx_qiling_crm_teams_department_id (department_id),
    KEY idx_qiling_crm_teams_leader_user_id (leader_user_id),
    KEY idx_qiling_crm_teams_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS qiling_crm_team_members (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    team_id BIGINT UNSIGNED NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    department_id BIGINT UNSIGNED DEFAULT NULL,
    member_role VARCHAR(30) NOT NULL DEFAULT 'member',
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    joined_at DATETIME NULL,
    created_by BIGINT UNSIGNED DEFAULT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_qiling_crm_team_members_team_user (team_id, user_id),
    KEY idx_qiling_crm_team_members_user_status (user_id, status),
    KEY idx_qiling_crm_team_members_department_id (department_id),
    KEY idx_qiling_crm_team_members_team_status (team_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS qiling_crm_dedupe_rules (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    entity_type VARCHAR(20) NOT NULL,
    match_mobile TINYINT(1) NOT NULL DEFAULT 1,
    match_email TINYINT(1) NOT NULL DEFAULT 1,
    match_company TINYINT(1) NOT NULL DEFAULT 0,
    enabled TINYINT(1) NOT NULL DEFAULT 1,
    updated_by BIGINT UNSIGNED DEFAULT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_qiling_crm_dedupe_rules_entity_type (entity_type),
    KEY idx_qiling_crm_dedupe_rules_enabled (enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS qiling_crm_custom_fields (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    entity_type VARCHAR(20) NOT NULL,
    field_key VARCHAR(60) NOT NULL,
    field_label VARCHAR(120) NOT NULL,
    field_type VARCHAR(30) NOT NULL DEFAULT 'text',
    options_json JSON NULL,
    default_value TEXT NULL,
    placeholder VARCHAR(160) NOT NULL DEFAULT '',
    is_required TINYINT(1) NOT NULL DEFAULT 0,
    sort_order INT NOT NULL DEFAULT 100,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    created_by BIGINT UNSIGNED DEFAULT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_qiling_crm_custom_fields_entity_key (entity_type, field_key),
    KEY idx_qiling_crm_custom_fields_entity_status_sort (entity_type, status, sort_order, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS qiling_crm_form_configs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    entity_type VARCHAR(20) NOT NULL,
    layout_json JSON NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    updated_by BIGINT UNSIGNED DEFAULT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_qiling_crm_form_configs_entity_type (entity_type),
    KEY idx_qiling_crm_form_configs_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS qiling_crm_reminder_rules (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    rule_code VARCHAR(40) NOT NULL,
    rule_name VARCHAR(120) NOT NULL,
    remind_type VARCHAR(20) NOT NULL DEFAULT 'schedule',
    offset_minutes INT NOT NULL DEFAULT 0,
    enabled TINYINT(1) NOT NULL DEFAULT 1,
    created_by BIGINT UNSIGNED DEFAULT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_qiling_crm_reminder_rules_code (rule_code),
    KEY idx_qiling_crm_reminder_rules_type_enabled (remind_type, enabled, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS qiling_crm_notifications (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    user_id BIGINT UNSIGNED NOT NULL,
    activity_id BIGINT UNSIGNED DEFAULT NULL,
    entity_type VARCHAR(20) NOT NULL DEFAULT 'activity',
    entity_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    reminder_type VARCHAR(20) NOT NULL DEFAULT 'schedule',
    title VARCHAR(180) NOT NULL DEFAULT '',
    content TEXT NULL,
    due_at DATETIME NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'unread',
    sent_at DATETIME NULL,
    read_at DATETIME NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_qiling_crm_notifications_activity_type_user (activity_id, reminder_type, user_id),
    KEY idx_qiling_crm_notifications_user_status_due (user_id, status, due_at, id),
    KEY idx_qiling_crm_notifications_status_created (status, created_at, id),
    KEY idx_qiling_crm_notifications_entity (entity_type, entity_id, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS qiling_customer_crm_links (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    customer_id BIGINT UNSIGNED NOT NULL,
    crm_contact_id BIGINT UNSIGNED DEFAULT NULL,
    crm_company_id BIGINT UNSIGNED DEFAULT NULL,
    match_rule VARCHAR(30) NOT NULL DEFAULT 'manual',
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    note VARCHAR(255) NOT NULL DEFAULT '',
    created_by BIGINT UNSIGNED DEFAULT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_qiling_customer_crm_links_customer_contact (customer_id, crm_contact_id),
    UNIQUE KEY uq_qiling_customer_crm_links_customer_company (customer_id, crm_company_id),
    KEY idx_qiling_customer_crm_links_customer_status_id (customer_id, status, id),
    KEY idx_qiling_customer_crm_links_contact_status_id (crm_contact_id, status, id),
    KEY idx_qiling_customer_crm_links_company_status_id (crm_company_id, status, id),
    KEY idx_qiling_customer_crm_links_updated_at (updated_at),
    KEY idx_qiling_customer_crm_links_created_by_id (created_by, id),
    CONSTRAINT fk_qiling_customer_crm_links_customer FOREIGN KEY (customer_id) REFERENCES qiling_customers(id) ON DELETE CASCADE,
    CONSTRAINT fk_qiling_customer_crm_links_contact FOREIGN KEY (crm_contact_id) REFERENCES qiling_crm_contacts(id) ON DELETE SET NULL,
    CONSTRAINT fk_qiling_customer_crm_links_company FOREIGN KEY (crm_company_id) REFERENCES qiling_crm_companies(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS qiling_crm_products (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    product_code VARCHAR(40) NOT NULL,
    product_name VARCHAR(150) NOT NULL,
    category VARCHAR(80) NOT NULL DEFAULT '',
    currency_code VARCHAR(8) NOT NULL DEFAULT 'CNY',
    list_price DECIMAL(14,2) NOT NULL DEFAULT 0.00,
    unit VARCHAR(20) NOT NULL DEFAULT '项',
    tax_rate DECIMAL(6,2) NOT NULL DEFAULT 0.00,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    description TEXT NULL,
    created_by BIGINT UNSIGNED DEFAULT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_qiling_crm_products_code (product_code),
    KEY idx_qiling_crm_products_status_id (status, id),
    KEY idx_qiling_crm_products_category_id (category, id),
    KEY idx_qiling_crm_products_created_by_id (created_by, id),
    FULLTEXT KEY ft_qiling_crm_products_name (product_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS qiling_crm_quotes (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    quote_no VARCHAR(40) NOT NULL,
    deal_id BIGINT UNSIGNED NOT NULL,
    company_id BIGINT UNSIGNED DEFAULT NULL,
    contact_id BIGINT UNSIGNED DEFAULT NULL,
    owner_user_id BIGINT UNSIGNED DEFAULT NULL,
    currency_code VARCHAR(8) NOT NULL DEFAULT 'CNY',
    subtotal_amount DECIMAL(14,2) NOT NULL DEFAULT 0.00,
    discount_amount DECIMAL(14,2) NOT NULL DEFAULT 0.00,
    tax_amount DECIMAL(14,2) NOT NULL DEFAULT 0.00,
    total_amount DECIMAL(14,2) NOT NULL DEFAULT 0.00,
    status VARCHAR(20) NOT NULL DEFAULT 'draft',
    valid_until DATE NULL,
    remark VARCHAR(500) NOT NULL DEFAULT '',
    created_by BIGINT UNSIGNED DEFAULT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_qiling_crm_quotes_no (quote_no),
    KEY idx_qiling_crm_quotes_deal_status_id (deal_id, status, id),
    KEY idx_qiling_crm_quotes_owner_status_id (owner_user_id, status, id),
    KEY idx_qiling_crm_quotes_company_id (company_id),
    KEY idx_qiling_crm_quotes_contact_id (contact_id),
    KEY idx_qiling_crm_quotes_valid_until (valid_until),
    CONSTRAINT fk_qiling_crm_quotes_deal FOREIGN KEY (deal_id) REFERENCES qiling_crm_deals(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS qiling_crm_quote_items (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    quote_id BIGINT UNSIGNED NOT NULL,
    product_id BIGINT UNSIGNED DEFAULT NULL,
    item_name VARCHAR(160) NOT NULL DEFAULT '',
    quantity DECIMAL(12,2) NOT NULL DEFAULT 1.00,
    unit_price DECIMAL(14,2) NOT NULL DEFAULT 0.00,
    discount_rate DECIMAL(6,2) NOT NULL DEFAULT 0.00,
    tax_rate DECIMAL(6,2) NOT NULL DEFAULT 0.00,
    line_amount DECIMAL(14,2) NOT NULL DEFAULT 0.00,
    remark VARCHAR(255) NOT NULL DEFAULT '',
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY idx_qiling_crm_quote_items_quote_id (quote_id),
    KEY idx_qiling_crm_quote_items_product_id (product_id),
    CONSTRAINT fk_qiling_crm_quote_items_quote FOREIGN KEY (quote_id) REFERENCES qiling_crm_quotes(id) ON DELETE CASCADE,
    CONSTRAINT fk_qiling_crm_quote_items_product FOREIGN KEY (product_id) REFERENCES qiling_crm_products(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS qiling_crm_contracts (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    contract_no VARCHAR(40) NOT NULL,
    deal_id BIGINT UNSIGNED NOT NULL,
    quote_id BIGINT UNSIGNED DEFAULT NULL,
    company_id BIGINT UNSIGNED DEFAULT NULL,
    contact_id BIGINT UNSIGNED DEFAULT NULL,
    owner_user_id BIGINT UNSIGNED DEFAULT NULL,
    currency_code VARCHAR(8) NOT NULL DEFAULT 'CNY',
    total_amount DECIMAL(14,2) NOT NULL DEFAULT 0.00,
    signed_at DATETIME NULL,
    effective_at DATETIME NULL,
    expire_at DATETIME NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'draft',
    remark VARCHAR(500) NOT NULL DEFAULT '',
    created_by BIGINT UNSIGNED DEFAULT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_qiling_crm_contracts_no (contract_no),
    KEY idx_qiling_crm_contracts_deal_status_id (deal_id, status, id),
    KEY idx_qiling_crm_contracts_owner_status_id (owner_user_id, status, id),
    KEY idx_qiling_crm_contracts_quote_id (quote_id),
    KEY idx_qiling_crm_contracts_signed_at (signed_at),
    CONSTRAINT fk_qiling_crm_contracts_deal FOREIGN KEY (deal_id) REFERENCES qiling_crm_deals(id) ON DELETE CASCADE,
    CONSTRAINT fk_qiling_crm_contracts_quote FOREIGN KEY (quote_id) REFERENCES qiling_crm_quotes(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS qiling_crm_contract_items (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    contract_id BIGINT UNSIGNED NOT NULL,
    product_id BIGINT UNSIGNED DEFAULT NULL,
    item_name VARCHAR(160) NOT NULL DEFAULT '',
    quantity DECIMAL(12,2) NOT NULL DEFAULT 1.00,
    unit_price DECIMAL(14,2) NOT NULL DEFAULT 0.00,
    discount_rate DECIMAL(6,2) NOT NULL DEFAULT 0.00,
    tax_rate DECIMAL(6,2) NOT NULL DEFAULT 0.00,
    line_amount DECIMAL(14,2) NOT NULL DEFAULT 0.00,
    remark VARCHAR(255) NOT NULL DEFAULT '',
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY idx_qiling_crm_contract_items_contract_id (contract_id),
    KEY idx_qiling_crm_contract_items_product_id (product_id),
    CONSTRAINT fk_qiling_crm_contract_items_contract FOREIGN KEY (contract_id) REFERENCES qiling_crm_contracts(id) ON DELETE CASCADE,
    CONSTRAINT fk_qiling_crm_contract_items_product FOREIGN KEY (product_id) REFERENCES qiling_crm_products(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS qiling_crm_payment_plans (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    contract_id BIGINT UNSIGNED NOT NULL,
    deal_id BIGINT UNSIGNED NOT NULL,
    milestone_name VARCHAR(120) NOT NULL DEFAULT '',
    due_date DATE NULL,
    amount DECIMAL(14,2) NOT NULL DEFAULT 0.00,
    paid_amount DECIMAL(14,2) NOT NULL DEFAULT 0.00,
    currency_code VARCHAR(8) NOT NULL DEFAULT 'CNY',
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    paid_at DATETIME NULL,
    payment_note VARCHAR(255) NOT NULL DEFAULT '',
    created_by BIGINT UNSIGNED DEFAULT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY idx_qiling_crm_payment_plans_contract_status_due (contract_id, status, due_date, id),
    KEY idx_qiling_crm_payment_plans_deal_status_due (deal_id, status, due_date, id),
    KEY idx_qiling_crm_payment_plans_status_due (status, due_date),
    CONSTRAINT fk_qiling_crm_payment_plans_contract FOREIGN KEY (contract_id) REFERENCES qiling_crm_contracts(id) ON DELETE CASCADE,
    CONSTRAINT fk_qiling_crm_payment_plans_deal FOREIGN KEY (deal_id) REFERENCES qiling_crm_deals(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS qiling_crm_invoices (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    invoice_no VARCHAR(60) NOT NULL,
    contract_id BIGINT UNSIGNED NOT NULL,
    deal_id BIGINT UNSIGNED NOT NULL,
    company_id BIGINT UNSIGNED DEFAULT NULL,
    amount DECIMAL(14,2) NOT NULL DEFAULT 0.00,
    currency_code VARCHAR(8) NOT NULL DEFAULT 'CNY',
    issue_date DATE NULL,
    due_date DATE NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'draft',
    receiver_name VARCHAR(120) NOT NULL DEFAULT '',
    receiver_tax_no VARCHAR(80) NOT NULL DEFAULT '',
    note VARCHAR(500) NOT NULL DEFAULT '',
    created_by BIGINT UNSIGNED DEFAULT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_qiling_crm_invoices_no (invoice_no),
    KEY idx_qiling_crm_invoices_contract_status_id (contract_id, status, id),
    KEY idx_qiling_crm_invoices_deal_status_id (deal_id, status, id),
    KEY idx_qiling_crm_invoices_issue_date (issue_date),
    KEY idx_qiling_crm_invoices_due_date (due_date),
    CONSTRAINT fk_qiling_crm_invoices_contract FOREIGN KEY (contract_id) REFERENCES qiling_crm_contracts(id) ON DELETE CASCADE,
    CONSTRAINT fk_qiling_crm_invoices_deal FOREIGN KEY (deal_id) REFERENCES qiling_crm_deals(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS qiling_crm_automation_rules (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    rule_name VARCHAR(120) NOT NULL,
    entity_type VARCHAR(20) NOT NULL DEFAULT 'deal',
    trigger_field VARCHAR(30) NOT NULL DEFAULT 'status',
    trigger_from VARCHAR(40) NOT NULL DEFAULT '',
    trigger_to VARCHAR(40) NOT NULL DEFAULT '',
    action_type VARCHAR(30) NOT NULL DEFAULT 'create_task',
    action_config_json JSON NULL,
    sort_order INT NOT NULL DEFAULT 100,
    enabled TINYINT(1) NOT NULL DEFAULT 1,
    created_by BIGINT UNSIGNED DEFAULT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_qiling_crm_automation_rules_unique (entity_type, trigger_field, trigger_from, trigger_to, action_type, sort_order, rule_name),
    KEY idx_qiling_crm_automation_rules_entity_trigger_enabled (entity_type, trigger_field, enabled, sort_order, id),
    KEY idx_qiling_crm_automation_rules_action_enabled (action_type, enabled, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS qiling_crm_automation_logs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    rule_id BIGINT UNSIGNED NOT NULL,
    entity_type VARCHAR(20) NOT NULL DEFAULT '',
    entity_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    trigger_field VARCHAR(30) NOT NULL DEFAULT '',
    trigger_from VARCHAR(40) NOT NULL DEFAULT '',
    trigger_to VARCHAR(40) NOT NULL DEFAULT '',
    action_type VARCHAR(30) NOT NULL DEFAULT '',
    status VARCHAR(20) NOT NULL DEFAULT 'success',
    message VARCHAR(500) NOT NULL DEFAULT '',
    payload_json JSON NULL,
    response_json JSON NULL,
    executed_by BIGINT UNSIGNED DEFAULT NULL,
    executed_at DATETIME NOT NULL,
    created_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY idx_qiling_crm_automation_logs_rule_time (rule_id, executed_at, id),
    KEY idx_qiling_crm_automation_logs_entity_time (entity_type, entity_id, executed_at, id),
    KEY idx_qiling_crm_automation_logs_status_time (status, executed_at, id),
    CONSTRAINT fk_qiling_crm_automation_logs_rule FOREIGN KEY (rule_id) REFERENCES qiling_crm_automation_rules(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS qiling_crm_deal_stage_logs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    deal_id BIGINT UNSIGNED NOT NULL,
    pipeline_key VARCHAR(40) NOT NULL DEFAULT 'default',
    from_stage_key VARCHAR(40) NOT NULL DEFAULT '',
    to_stage_key VARCHAR(40) NOT NULL DEFAULT '',
    from_status VARCHAR(20) NOT NULL DEFAULT '',
    to_status VARCHAR(20) NOT NULL DEFAULT '',
    duration_seconds INT NOT NULL DEFAULT 0,
    changed_by BIGINT UNSIGNED DEFAULT NULL,
    changed_at DATETIME NOT NULL,
    created_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY idx_qiling_crm_deal_stage_logs_deal_time (deal_id, changed_at, id),
    KEY idx_qiling_crm_deal_stage_logs_pipeline_stage_time (pipeline_key, to_stage_key, changed_at, id),
    KEY idx_qiling_crm_deal_stage_logs_from_stage_time (from_stage_key, changed_at, id),
    CONSTRAINT fk_qiling_crm_deal_stage_logs_deal FOREIGN KEY (deal_id) REFERENCES qiling_crm_deals(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS qiling_push_channels (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    channel_code VARCHAR(50) NOT NULL,
    channel_name VARCHAR(100) NOT NULL,
    provider VARCHAR(30) NOT NULL,
    webhook_url VARCHAR(1000) NOT NULL,
    secret VARCHAR(255) NOT NULL DEFAULT '',
    keyword VARCHAR(100) NOT NULL DEFAULT '',
    security_mode VARCHAR(20) NOT NULL DEFAULT 'auto',
    enabled TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_qiling_push_channels_code (channel_code),
    KEY idx_qiling_push_channels_provider (provider),
    KEY idx_qiling_push_channels_enabled (enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS qiling_push_logs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    channel_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    provider VARCHAR(30) NOT NULL DEFAULT '',
    status VARCHAR(20) NOT NULL DEFAULT '',
    response_code INT NOT NULL DEFAULT 0,
    request_payload TEXT NULL,
    response_body TEXT NULL,
    error_message VARCHAR(1000) NOT NULL DEFAULT '',
    trigger_source VARCHAR(50) NOT NULL DEFAULT '',
    task_id BIGINT UNSIGNED DEFAULT NULL,
    created_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY idx_qiling_push_logs_channel_id (channel_id),
    KEY idx_qiling_push_logs_status (status),
    KEY idx_qiling_push_logs_task_id (task_id),
    KEY idx_qiling_push_logs_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS qiling_wp_users (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    wp_user_id BIGINT UNSIGNED NOT NULL,
    username VARCHAR(60) NOT NULL,
    email VARCHAR(120) NOT NULL,
    display_name VARCHAR(120) NOT NULL DEFAULT '',
    roles_json JSON NULL,
    meta_json JSON NULL,
    synced_at DATETIME NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_qiling_wp_users_wp_user_id (wp_user_id),
    KEY idx_qiling_wp_users_email (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS qiling_customer_grades (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    store_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    grade_code VARCHAR(40) NOT NULL,
    grade_name VARCHAR(100) NOT NULL,
    threshold_points INT NOT NULL DEFAULT 0,
    discount_rate DECIMAL(5,2) NOT NULL DEFAULT 100.00,
    enabled TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_qiling_customer_grades_store_code (store_id, grade_code),
    KEY idx_qiling_customer_grades_store_id (store_id),
    KEY idx_qiling_customer_grades_enabled (enabled),
    KEY idx_qiling_customer_grades_threshold_points (threshold_points)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS qiling_customer_point_accounts (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    customer_id BIGINT UNSIGNED NOT NULL,
    current_points INT NOT NULL DEFAULT 0,
    lifetime_points INT NOT NULL DEFAULT 0,
    grade_id BIGINT UNSIGNED DEFAULT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_qiling_customer_point_accounts_customer_id (customer_id),
    KEY idx_qiling_customer_point_accounts_grade_id (grade_id),
    CONSTRAINT fk_qiling_customer_point_accounts_customer FOREIGN KEY (customer_id) REFERENCES qiling_customers(id) ON DELETE CASCADE,
    CONSTRAINT fk_qiling_customer_point_accounts_grade FOREIGN KEY (grade_id) REFERENCES qiling_customer_grades(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS qiling_customer_point_logs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    customer_id BIGINT UNSIGNED NOT NULL,
    store_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    change_type VARCHAR(40) NOT NULL DEFAULT 'adjust',
    delta_points INT NOT NULL DEFAULT 0,
    before_points INT NOT NULL DEFAULT 0,
    after_points INT NOT NULL DEFAULT 0,
    operator_user_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    related_type VARCHAR(40) NOT NULL DEFAULT '',
    related_id BIGINT UNSIGNED DEFAULT NULL,
    note VARCHAR(255) NOT NULL DEFAULT '',
    created_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY idx_qiling_customer_point_logs_customer_id (customer_id),
    KEY idx_qiling_customer_point_logs_store_id (store_id),
    KEY idx_qiling_customer_point_logs_change_type (change_type),
    KEY idx_qiling_customer_point_logs_created_at (created_at),
    CONSTRAINT fk_qiling_customer_point_logs_customer FOREIGN KEY (customer_id) REFERENCES qiling_customers(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS qiling_open_gifts (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    store_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    trigger_type VARCHAR(40) NOT NULL DEFAULT 'onboard',
    gift_name VARCHAR(120) NOT NULL DEFAULT '',
    enabled TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_qiling_open_gifts_store_trigger (store_id, trigger_type),
    KEY idx_qiling_open_gifts_enabled (enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS qiling_open_gift_items (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    open_gift_id BIGINT UNSIGNED NOT NULL,
    item_type VARCHAR(30) NOT NULL DEFAULT 'points',
    points_value INT NOT NULL DEFAULT 0,
    coupon_name VARCHAR(120) NOT NULL DEFAULT '',
    coupon_type VARCHAR(20) NOT NULL DEFAULT 'cash',
    face_value DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    min_spend DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    remain_count INT NOT NULL DEFAULT 1,
    expire_days INT NOT NULL DEFAULT 30,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY idx_qiling_open_gift_items_open_gift_id (open_gift_id),
    KEY idx_qiling_open_gift_items_item_type (item_type),
    CONSTRAINT fk_qiling_open_gift_items_open_gift FOREIGN KEY (open_gift_id) REFERENCES qiling_open_gifts(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS qiling_open_gift_records (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    open_gift_id BIGINT UNSIGNED NOT NULL,
    trigger_type VARCHAR(40) NOT NULL DEFAULT 'onboard',
    customer_id BIGINT UNSIGNED NOT NULL,
    store_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    reference_type VARCHAR(40) NOT NULL DEFAULT '',
    reference_id BIGINT UNSIGNED DEFAULT NULL,
    operator_user_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    result_json JSON NULL,
    created_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_qiling_open_gift_records_trigger_customer (trigger_type, customer_id),
    KEY idx_qiling_open_gift_records_open_gift_id (open_gift_id),
    KEY idx_qiling_open_gift_records_store_id (store_id),
    KEY idx_qiling_open_gift_records_reference (reference_type, reference_id),
    CONSTRAINT fk_qiling_open_gift_records_open_gift FOREIGN KEY (open_gift_id) REFERENCES qiling_open_gifts(id) ON DELETE CASCADE,
    CONSTRAINT fk_qiling_open_gift_records_customer FOREIGN KEY (customer_id) REFERENCES qiling_customers(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS qiling_coupon_groups (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    store_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    group_code VARCHAR(40) NOT NULL,
    group_name VARCHAR(120) NOT NULL DEFAULT '',
    coupon_name VARCHAR(120) NOT NULL DEFAULT '',
    coupon_type VARCHAR(20) NOT NULL DEFAULT 'cash',
    face_value DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    min_spend DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    per_user_limit INT NOT NULL DEFAULT 1,
    total_limit INT NOT NULL DEFAULT 0,
    sent_total INT NOT NULL DEFAULT 0,
    expire_days INT NOT NULL DEFAULT 30,
    enabled TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_qiling_coupon_groups_store_code (store_id, group_code),
    KEY idx_qiling_coupon_groups_store_id (store_id),
    KEY idx_qiling_coupon_groups_enabled (enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS qiling_coupon_group_sends (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    group_id BIGINT UNSIGNED NOT NULL,
    customer_id BIGINT UNSIGNED NOT NULL,
    coupon_id BIGINT UNSIGNED NOT NULL,
    batch_no VARCHAR(40) NOT NULL DEFAULT '',
    operator_user_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL DEFAULT 'success',
    created_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY idx_qiling_coupon_group_sends_group_id (group_id),
    KEY idx_qiling_coupon_group_sends_customer_id (customer_id),
    KEY idx_qiling_coupon_group_sends_coupon_id (coupon_id),
    KEY idx_qiling_coupon_group_sends_batch_no (batch_no),
    CONSTRAINT fk_qiling_coupon_group_sends_group FOREIGN KEY (group_id) REFERENCES qiling_coupon_groups(id) ON DELETE CASCADE,
    CONSTRAINT fk_qiling_coupon_group_sends_customer FOREIGN KEY (customer_id) REFERENCES qiling_customers(id) ON DELETE CASCADE,
    CONSTRAINT fk_qiling_coupon_group_sends_coupon FOREIGN KEY (coupon_id) REFERENCES qiling_coupons(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS qiling_coupon_transfers (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    transfer_no VARCHAR(40) NOT NULL,
    coupon_id BIGINT UNSIGNED NOT NULL,
    from_customer_id BIGINT UNSIGNED NOT NULL,
    to_customer_id BIGINT UNSIGNED NOT NULL,
    from_store_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    to_store_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    operator_user_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    note VARCHAR(255) NOT NULL DEFAULT '',
    status VARCHAR(20) NOT NULL DEFAULT 'success',
    created_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_qiling_coupon_transfers_transfer_no (transfer_no),
    KEY idx_qiling_coupon_transfers_coupon_id (coupon_id),
    KEY idx_qiling_coupon_transfers_from_customer_id (from_customer_id),
    KEY idx_qiling_coupon_transfers_to_customer_id (to_customer_id),
    CONSTRAINT fk_qiling_coupon_transfers_coupon FOREIGN KEY (coupon_id) REFERENCES qiling_coupons(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS qiling_member_card_transfers (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    transfer_no VARCHAR(40) NOT NULL,
    member_card_id BIGINT UNSIGNED NOT NULL,
    from_customer_id BIGINT UNSIGNED NOT NULL,
    to_customer_id BIGINT UNSIGNED NOT NULL,
    from_store_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    to_store_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    operator_user_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    note VARCHAR(255) NOT NULL DEFAULT '',
    status VARCHAR(20) NOT NULL DEFAULT 'success',
    created_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_qiling_member_card_transfers_transfer_no (transfer_no),
    KEY idx_qiling_member_card_transfers_member_card_id (member_card_id),
    KEY idx_qiling_member_card_transfers_from_customer_id (from_customer_id),
    KEY idx_qiling_member_card_transfers_to_customer_id (to_customer_id),
    CONSTRAINT fk_qiling_member_card_transfers_member_card FOREIGN KEY (member_card_id) REFERENCES qiling_member_cards(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS qiling_printers (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    store_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    printer_code VARCHAR(40) NOT NULL,
    printer_name VARCHAR(120) NOT NULL DEFAULT '',
    provider VARCHAR(30) NOT NULL DEFAULT 'manual',
    endpoint VARCHAR(1000) NOT NULL DEFAULT '',
    api_key VARCHAR(255) NOT NULL DEFAULT '',
    enabled TINYINT(1) NOT NULL DEFAULT 1,
    last_status VARCHAR(20) NOT NULL DEFAULT '',
    last_error VARCHAR(500) NOT NULL DEFAULT '',
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_qiling_printers_store_code (store_id, printer_code),
    KEY idx_qiling_printers_store_id (store_id),
    KEY idx_qiling_printers_enabled (enabled)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS qiling_print_jobs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    store_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    printer_id BIGINT UNSIGNED DEFAULT NULL,
    job_no VARCHAR(40) NOT NULL,
    business_type VARCHAR(40) NOT NULL DEFAULT 'order_receipt',
    business_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    content TEXT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    response_body TEXT NULL,
    error_message VARCHAR(1000) NOT NULL DEFAULT '',
    operator_user_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_qiling_print_jobs_job_no (job_no),
    KEY idx_qiling_print_jobs_store_id (store_id),
    KEY idx_qiling_print_jobs_printer_id (printer_id),
    KEY idx_qiling_print_jobs_business (business_type, business_id),
    KEY idx_qiling_print_jobs_status (status),
    CONSTRAINT fk_qiling_print_jobs_printer FOREIGN KEY (printer_id) REFERENCES qiling_printers(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS qiling_audit_logs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    actor_user_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    action VARCHAR(80) NOT NULL,
    entity_type VARCHAR(80) NOT NULL,
    entity_id BIGINT UNSIGNED NOT NULL DEFAULT 0,
    message VARCHAR(255) NOT NULL DEFAULT '',
    context_json JSON NULL,
    created_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY idx_qiling_audit_logs_actor (actor_user_id),
    KEY idx_qiling_audit_logs_action (action),
    KEY idx_qiling_audit_logs_entity (entity_type, entity_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS qiling_system_settings (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    setting_key VARCHAR(100) NOT NULL,
    setting_value TEXT NULL,
    updated_by BIGINT UNSIGNED NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_qiling_system_settings_key (setting_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS qiling_password_reset_requests (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    user_id BIGINT UNSIGNED NOT NULL,
    channel VARCHAR(20) NOT NULL DEFAULT 'email',
    receiver VARCHAR(160) NOT NULL DEFAULT '',
    code_hash CHAR(64) NOT NULL,
    expire_at DATETIME NOT NULL,
    used_at DATETIME NULL,
    fail_count INT NOT NULL DEFAULT 0,
    request_ip VARCHAR(64) NOT NULL DEFAULT '',
    requested_at DATETIME NOT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY idx_qiling_pwd_reset_user (user_id, requested_at),
    KEY idx_qiling_pwd_reset_lookup (user_id, channel, receiver, used_at, id),
    KEY idx_qiling_pwd_reset_ip (request_ip, requested_at),
    KEY idx_qiling_pwd_reset_expire_used (expire_at, used_at),
    CONSTRAINT fk_qiling_pwd_reset_user FOREIGN KEY (user_id) REFERENCES qiling_users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
